<?xml version="1.0" encoding="utf-8"?><Database Name="AlquilerVehiculos" Class="CiudadesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=EQUIPO-ASUS;Initial Catalog=AlquilerVehiculos;Integrated Security=True" SettingsObjectName="Platform.Modeler.Properties.Settings" SettingsPropertyName="AlquilerVehiculosConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ciudad" Member="ciudad">
    <Type Name="ciudad">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="NVarChar(45)" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.ciudades" Method="ciudades">
    <ElementType Name="ciudadesResult">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="NVarChar(45)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.ciudad_nombre" Method="ciudad_nombre">
    <Parameter Name="nombre" Type="System.String" DbType="NVarChar(30)" />
    <ElementType Name="ciudad_nombreResult">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="NVarChar(45)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>