<?xml version="1.0" encoding="utf-8"?><Database Name="AlquilerVehiculos" Class="TipoDocumentoDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=EQUIPO-ASUS;Initial Catalog=AlquilerVehiculos;Integrated Security=True" SettingsObjectName="Platform.Modeler.Properties.Settings" SettingsPropertyName="AlquilerVehiculosConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tipo_documento" Member="tipo_documento">
    <Type Name="tipo_documento">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.tipo_documentos" Method="tipo_documentos">
    <ElementType Name="tipo_documentosResult">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.tipo_documentos_nombre" Method="tipo_documentos_nombre">
    <Parameter Name="nombre" Type="System.String" DbType="NVarChar(30)" />
    <ElementType Name="tipo_documentos_nombreResult">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>